import { useState } from 'react';
import {
  Sparkles,
  FileText,
  Download,
  Copy,
  Check,
  Loader2,
  Upload,
  Wand2,
  FileCheck,
  AlertCircle,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';

const reportTypes = [
  { value: 'eia', label: 'Environmental Impact Assessment Summary', icon: FileText },
  { value: 'audit', label: 'Environmental Audit Report', icon: FileCheck },
  { value: 'epp', label: 'Environmental Protection Plan', icon: Upload },
  { value: 'compliance', label: 'Compliance Status Report', icon: Check },
];

const mockGeneratedReport = `# ENVIRONMENTAL IMPACT ASSESSMENT SUMMARY

## Project: Dodoma Industrial Park Development

### 1. EXECUTIVE SUMMARY

This Environmental Impact Assessment (EIA) evaluates the potential environmental effects of the proposed Dodoma Industrial Park development project. The assessment was conducted in accordance with the Environmental Management Act (CAP 191) of Tanzania and NEMC guidelines.

### 2. PROJECT DESCRIPTION

**Location:** Dodoma Region, Tanzania  
**Project Type:** Industrial Development  
**Land Area:** 250 hectares  
**Estimated Investment:** $150 million

### 3. BASELINE ENVIRONMENTAL CONDITIONS

#### 3.1 Air Quality
- Current PM2.5 levels: 15 μg/m³ (within WHO guidelines)
- NO2 concentrations: 25 μg/m³
- SO2 levels: 8 μg/m³

#### 3.2 Water Resources
- Groundwater table depth: 45-60 meters
- Nearest water body: 2.5 km from project site
- Current water quality: Good (Class II)

#### 3.3 Biodiversity
- Vegetation type: Miombo woodland
- Key species: Acacia spp., Brachystegia spp.
- Wildlife presence: Moderate (small mammals, birds)

### 4. POTENTIAL IMPACTS

#### 4.1 Construction Phase
| Impact | Severity | Mitigation |
|--------|----------|------------|
| Dust emissions | Medium | Water spraying, dust suppression |
| Noise pollution | Medium | Equipment maintenance, time restrictions |
| Soil erosion | Low-Medium | Silt fences, revegetation |

#### 4.2 Operational Phase
| Impact | Severity | Mitigation |
|--------|----------|------------|
| Air emissions | Medium-High | Scrubbers, filters, monitoring |
| Wastewater | Medium | Treatment plant, recycling |
| Solid waste | Low-Medium | Segregation, recycling program |

### 5. MITIGATION MEASURES

1. **Air Quality Management**
   - Install continuous air quality monitoring stations
   - Implement emission control technologies
   - Regular equipment maintenance schedule

2. **Water Resource Protection**
   - Construct wastewater treatment facility
   - Implement rainwater harvesting systems
   - Groundwater monitoring program

3. **Biodiversity Conservation**
   - Set aside 20% of land as green buffer
   - Native tree planting program
   - Wildlife corridor preservation

### 6. ENVIRONMENTAL MANAGEMENT PLAN

**Phase 1 (Months 1-6):** Baseline monitoring, permit acquisition  
**Phase 2 (Months 7-18):** Construction with environmental controls  
**Phase 3 (Months 19+):** Operational monitoring, annual audits

### 7. CONCLUSION

With proper implementation of the recommended mitigation measures, the Dodoma Industrial Park development can proceed with minimal adverse environmental impacts. Continuous monitoring and adaptive management are essential for long-term environmental protection.

---
*Generated by BK Environmental AI Report Generator*  
*Date: ${new Date().toLocaleDateString()}*  
*Report ID: EIA-DOD-2024-001*
`;

export default function AIReportGenerator() {
  const [reportType, setReportType] = useState('');
  const [projectName, setProjectName] = useState('');
  const [projectLocation, setProjectLocation] = useState('');
  const [projectDescription, setProjectDescription] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [generatedReport, setGeneratedReport] = useState('');
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!reportType || !projectName) return;

    setIsGenerating(true);
    setProgress(0);
    setGeneratedReport('');

    // Simulate generation progress
    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          setIsGenerating(false);
          setGeneratedReport(mockGeneratedReport);
          return 100;
        }
        return prev + 10;
      });
    }, 300);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (format: 'pdf' | 'docx') => {
    const blob = new Blob([generatedReport], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `environmental-report-${new Date().toISOString().split('T')[0]}.${format === 'pdf' ? 'txt' : 'txt'}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#0a1f12] p-4 lg:p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-eco-500 flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-heading font-bold text-white">
                  AI Report Generator
                </h1>
                <p className="text-gray-400 text-sm">
                  Generate professional environmental reports with AI assistance
                </p>
              </div>
            </div>
            <Button
              variant="ghost"
              onClick={() => window.location.hash = ''}
              className="text-gray-400 hover:text-eco-400 transition-colors"
            >
              ← Back to Home
            </Button>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          {/* Input Form */}
          <Card className="bg-[#0f2e15] border-eco-500/20">
            <CardHeader>
              <CardTitle className="text-white">Report Configuration</CardTitle>
              <CardDescription className="text-gray-400">
                Provide project details to generate a customized report
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Report Type */}
              <div>
                <label className="text-sm text-gray-300 mb-2 block">Report Type *</label>
                <Select value={reportType} onValueChange={setReportType}>
                  <SelectTrigger className="bg-[#0a1f12] border-eco-500/30 text-white">
                    <SelectValue placeholder="Select report type" />
                  </SelectTrigger>
                  <SelectContent className="bg-[#0f2e15] border-eco-500/30">
                    {reportTypes.map((type) => (
                      <SelectItem
                        key={type.value}
                        value={type.value}
                        className="text-white hover:bg-eco-500/20"
                      >
                        <div className="flex items-center gap-2">
                          <type.icon className="w-4 h-4 text-eco-400" />
                          {type.label}
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Project Name */}
              <div>
                <label className="text-sm text-gray-300 mb-2 block">Project Name *</label>
                <Input
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                  placeholder="e.g., Dodoma Industrial Park"
                  className="bg-[#0a1f12] border-eco-500/30 text-white placeholder:text-gray-500"
                />
              </div>

              {/* Project Location */}
              <div>
                <label className="text-sm text-gray-300 mb-2 block">Project Location</label>
                <Input
                  value={projectLocation}
                  onChange={(e) => setProjectLocation(e.target.value)}
                  placeholder="e.g., Dodoma, Tanzania"
                  className="bg-[#0a1f12] border-eco-500/30 text-white placeholder:text-gray-500"
                />
              </div>

              {/* Project Description */}
              <div>
                <label className="text-sm text-gray-300 mb-2 block">Project Description</label>
                <Textarea
                  value={projectDescription}
                  onChange={(e) => setProjectDescription(e.target.value)}
                  placeholder="Describe the project scope, activities, and any specific environmental concerns..."
                  className="bg-[#0a1f12] border-eco-500/30 text-white placeholder:text-gray-500 min-h-[120px]"
                />
              </div>

              {/* File Upload */}
              <div>
                <label className="text-sm text-gray-300 mb-2 block">Supporting Documents (Optional)</label>
                <div className="border-2 border-dashed border-eco-500/30 rounded-xl p-6 text-center hover:border-eco-500/50 transition-colors cursor-pointer">
                  <Upload className="w-8 h-8 text-eco-400 mx-auto mb-2" />
                  <p className="text-gray-400 text-sm">Drag and drop files here or click to browse</p>
                  <p className="text-gray-500 text-xs mt-1">PDF, Word, Excel, Images up to 50MB</p>
                </div>
              </div>

              {/* Generate Button */}
              <Button
                onClick={handleGenerate}
                disabled={!reportType || !projectName || isGenerating}
                className="w-full bg-gradient-to-r from-purple-600 to-eco-600 hover:from-purple-500 hover:to-eco-500 text-white py-3 rounded-xl disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    Generating Report...
                  </>
                ) : (
                  <>
                    <Wand2 className="w-5 h-5 mr-2" />
                    Generate Report
                  </>
                )}
              </Button>

              {/* Progress */}
              {isGenerating && (
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-400">Generating report...</span>
                    <span className="text-eco-400">{progress}%</span>
                  </div>
                  <Progress value={progress} className="h-2" />
                </div>
              )}
            </CardContent>
          </Card>

          {/* Output Section */}
          <Card className="bg-[#0f2e15] border-eco-500/20">
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle className="text-white">Generated Report</CardTitle>
                <CardDescription className="text-gray-400">
                  Preview and download your report
                </CardDescription>
              </div>
              {generatedReport && (
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleCopy}
                    className="border-eco-500/30 text-gray-300 hover:text-white"
                  >
                    {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  </Button>
                </div>
              )}
            </CardHeader>
            <CardContent>
              {generatedReport ? (
                <div className="space-y-4">
                  {/* Report Preview */}
                  <div className="bg-[#0a1f12] rounded-xl p-4 max-h-[400px] overflow-auto">
                    <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono">
                      {generatedReport}
                    </pre>
                  </div>

                  {/* Download Options */}
                  <Tabs defaultValue="pdf" className="w-full">
                    <TabsList className="grid w-full grid-cols-2 bg-[#0a1f12]">
                      <TabsTrigger value="pdf" className="data-[state=active]:bg-eco-500/20">
                        PDF Format
                      </TabsTrigger>
                      <TabsTrigger value="docx" className="data-[state=active]:bg-eco-500/20">
                        Word Format
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent value="pdf" className="mt-4">
                      <Button
                        onClick={() => handleDownload('pdf')}
                        className="w-full btn-primary"
                      >
                        <Download className="w-4 h-4 mr-2" />
                        Download as PDF
                      </Button>
                    </TabsContent>
                    <TabsContent value="docx" className="mt-4">
                      <Button
                        onClick={() => handleDownload('docx')}
                        className="w-full btn-primary"
                      >
                        <Download className="w-4 h-4 mr-2" />
                        Download as Word Document
                      </Button>
                    </TabsContent>
                  </Tabs>
                </div>
              ) : (
                <div className="text-center py-16">
                  <div className="w-20 h-20 rounded-full bg-eco-500/10 flex items-center justify-center mx-auto mb-4">
                    <FileText className="w-10 h-10 text-eco-400/50" />
                  </div>
                  <p className="text-gray-400">
                    Your generated report will appear here
                  </p>
                  <p className="text-gray-500 text-sm mt-1">
                    Fill in the details and click Generate Report
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Tips Section */}
        <Card className="mt-6 bg-[#0f2e15] border-eco-500/20">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-eco-400" />
              Tips for Better Results
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {[
                'Provide detailed project descriptions for more accurate reports',
                'Include specific location data for localized environmental factors',
                'Upload baseline data and previous reports for context',
                'Specify industry type for relevant regulatory requirements',
                'Mention any known environmental concerns or sensitive areas',
                'Include project timeline for phase-appropriate recommendations',
              ].map((tip, index) => (
                <div
                  key={index}
                  className="flex items-start gap-2 p-3 rounded-lg bg-[#0a1f12] border border-eco-500/10"
                >
                  <Check className="w-4 h-4 text-eco-400 flex-shrink-0 mt-0.5" />
                  <span className="text-sm text-gray-300">{tip}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
